### ISSUE TITLE
pythagorean-triplet: improve readme and specification

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#1211] opened 2018-03-24 20:52 UTC
@yawpitch submitted this over in https://github.com/exercism/exercism.io/issues/3743

---- 

I'm working on the Python track specifically, but I notice that across many of the language tracks the tests and examples do not reflect the description of the problem:

> Pythagorean Triplet
> A Pythagorean triplet is a set of three natural numbers, {a, b, c}, for which,
> `a**2 + b**2 = c**2`
> For example,
> `3**2 + 4**2 = 9 + 16 = 25 = 5**2`.
> There exists exactly one Pythagorean triplet for which a + b + c = 1000.
> Find the product `a * b * c`.

In the Python, Rust, and Haskell tracks, for instance, there are no tests whatsoever related to the "find the product `a*b*c`" statement, and all three require different constructs than what's implied by the problem description and title. The Javascript track, however, does require that the work produced can calculate the product.

**Comment by petertseng** [comment] 2018-03-30 22:06
Since we made different design choices than Project Euler and, as a result of the choices, we are not limited to validating a single numerical answer, I suggest we do away with finding the product.

There are choices for parameterisation:

* Only find the single triplet where a + b + c = 1000
* Find triplets where a + b + c = N
* Find triplets where a + b + c < N
* Find triplets where a < N and b < N and c < N
* I"m sure one can find more options if you just look through http://exercism.io/contribute/canonical-data/pythagorean-triplet but I'm not going to do that.
* Decide the problem is not a good fit for exercism and decide to deprecate it

"Only find the single triplet where a + b + c = 1000" is my least-preferred option. I do not see a need for me to express an ordering between any other options at this time.

**Comment by petertseng** [comment] 2018-03-30 22:07
EBWODP

> I suggest we do away with finding the product.

I suggest test suites simply check the values of `a`, `b` and `c` that a test case will specify.

**Comment by petertseng** [comment] 2018-08-21 19:41
Hey there, just editing the initial issue description to put backticks around the asterisks, otherwise something like `a*b*c` turns into a*b*c and `a**2 + b**2 = c**2` turns into a**2 + b**2 = c**2 which is not what we want to show in this issue (it would decrease understanding)

**Comment by felix91gr** [comment] 2018-08-24 21:31
> What test cases shall we recommend?

Checking the solution is much easier if we can ask to be given a, b and c.

**Comment by petertseng** [comment] 2018-10-11 18:51
Update on status of this issue: The canonical tests are created in https://github.com/exercism/problem-specifications/pull/1332.

A person who wants to close this issue should update https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/description.md to match the new task (given N, find any pythagorean triplets whose sum is N).

Don't forget to use one of the words in https://help.github.com/articles/closing-issues-using-keywords/  in your commit message.

**Closed** 2018-11-20 09:58 UTC
