### ISSUE TITLE
RNA Transcription: source gives slightly different problem definition

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/problem-specifications#1078] opened 2018-01-07 17:48 UTC
As per [exercism.io/#3705](https://github.com/exercism/exercism.io/issues/3705):

> Looking through the problem statement found on Exercism vs the problem statement found on ROSALIND (which is linked to as the source in the README.md), the problem on Exercism is incorrect.
>
> The transcription would actually be as follows, according to http://rosalind.info/problems/rna/:
>
> * `G` -> `G`
> * `C` -> `C`
> * `T` -> `U`
> * `A` -> `A`
>
> The complements listed on Exercism are as follows:
>
> * `G` -> `C`
> * `C` -> `G`
> * `T` -> `A`
> * `A` -> `U`
>
> My guess is the source might be http://rosalind.info/problems/revc/ instead, which is a related problem which closely matches but still isn't quite the same as the premise here.

I'm not too informed on biology, so I don't know if this exercise has been implemented incorrectly, or if it is just that the source isn't quite right (I expect the second option).

**Comment by rpottsoh** [comment] 2018-01-17 22:55
I can open a PR to update this exercise.  Kind of a shame, it is almost a 1:1 relationship between DNA and RNA.

**Comment by petertseng** [comment] 2018-01-18 00:27
If we change to T -> U, we will undo the change done in https://github.com/exercism/exercism.io/issues/1310 . Please confirm intent to do this.

**Comment by petertseng** [comment] 2018-01-18 00:39
If it is changed back to T -> U, someone may file an issue similar to https://github.com/exercism/exercism.io/issues/791 or https://github.com/exercism/exercism.io/issues/1298 again. Be prepared for this to happen, and decide beforehand which is correct.

Please don't use my comment to justify a "we should make no change because that's the way things always have been" response. If no action is taken, it should be justified along the lines of "this is what we believe the correct definition of RNA transcription is"

**Comment by petertseng** [comment] 2018-01-18 00:47
> If no action is taken

EBWODP: Whatever action or non-action we take.

**Comment by rpottsoh** [comment] 2018-01-18 01:47
@petertseng thanks for bringing these past issues to light.

exercism/exercism.io#791 refers to the same site that @sjwarner-bp mentions at the beginning of this issue.  exercism/exercism.io#1298 was superceded by exercism/exercism.io#1310 which references commit [175c65e](https://github.com/exercism/exercism.io/commit/175c65e3f7d3776fe2c9bd981222d8a7c6e94a3c) which just seems to change the DNA => RNA map with no reason given.  The source_link found in the the .yml file in the aforementioned commit follows the same rules indicated at the opening of this issue and doesn't agree with README.

Why was the README changed?  The sources that have been provided all contradict the change that was made in the commit mentioned in exercism/exercism.io#1310.

So I am left wondering why was the README changed, and what source information was followed to guide that change?

Yes, I think the exercise is easier by making these proposed changes to this exercise.  But what is more important, being right or just being more difficult?

If the later, why does it have to be an RNA Transription?  Why not a FizzBot => GilPom transcription?

It seems to me that we need a source that shows that the README is accurate as is, otherwise the exercise should be updated to agree with the sources that we are aware of.

**Comment by rpottsoh** [comment] 2018-01-18 02:05
I have found another source:
http://www.fr33.net/seqedit.php
This is a sequence editor that follows several methods.  The exercise appears to be following the `Complement` method.  The proposed change would be changing to the T to U method.  

I think the minimum change that should occur would be to update or remove the Source_link in metadata.yml.  

The README already alludes to using the complement method but I think could be worded better to be less ambiguous.

Let me know your thoughts on all this.  I'll leave #1133 open a little while longer, but likely it should be closed.

**Comment by rpottsoh** [comment] 2018-01-22 16:21
@martinfreedman I believe you are interested in seeing test cases added to rna-transcription, specifically related to transposing RNA to DNA.  Would you be willing to submit a PR that includes new cases to the [testdata](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json)?  Up to this point my involvement is limited to resolving the issue opened above, that I believe can be handled by updating metadata.yml, see PR #1134.   It is not meant to address your desire to see other cases added to the testdata.

**Comment by martinfreedman** [comment] 2018-01-22 17:14
I am not sure how I was brought into this issue, but we are discussing the same exercise. 

The sequence editor just linked does not do transcription directly, using the complement function is not the same (except when combined with T->U/U->T). 

This was my favourite easy exercise - amongst many that is was getting boring. To change this because ignorant people have never heard of reverse_transcriptase is ridiculous.

" Why not a FizzBot => GilPom transcription?" Why not indeed. But the original was fine,  it is just an exercise! I thought the objective was to have a transcript method that works in both directions. That was the only challenge of this test. Otherwise use a dictionary or whatever... pointless.

If you are requesting a PR I am happy to do it but the readme must match. Is that being done too? Or do you want me to do that too? (no probs if so).

**Comment by martinfreedman** [comment] 2018-01-23 16:19
Apart from the mismap from T to A, rather than U, the original version of this exercise was fine. As an easy  programming exercise  I found it interesting especially compared to many others on the early stage of the track.

What is nice to have is knowing that a challenge is the basis, possibly, for some real world application. I think that engages the novice in realising the practicality of the challenges. Of course they are not expected to gain much, if any, real knowledge of the applied topic.

What I found very annoying with exercise was that it was entirely changed, to a much more basic challenge, due to, and I mean this neutrally, biological ignorance. The change was more than pointless - an addition to the readme would have sufficed (that this was not "biologically accurate").

I am happy to do the PRs for test schema and readme but first, considering there was considerable discussion to change it to make it more (incorrectly as it turns out) "biologically plausible", I want reassurance that I am not wasting my time and causing further pointless discussion.

**Comment by rpottsoh** [comment] 2018-01-23 16:44
For me, I think it would not be time wasted if your proposed changes:
-  Keep @coriolinus's [comment](https://github.com/exercism/problem-specifications/issues/1078#issuecomment-359506187) in mind.
-  Alleviate the confusion that seems to reoccur and I think has allowed for inconsistencies between metadata, README, and testdata to creep in. 
- Introduce new cases that explore transposing RNA to DNA.

You might consider starting with opening a new issue that would give a sample of the types changes (additions) you are considering for the testdata, as well as your thoughts about changes you are considering for description.md and metadata.yml.  Dip your toe before you jump in.

**Comment by martinfreedman** [comment] 2018-01-23 19:40
Thanks, will do when I am next free

**Closed** 2018-01-25 14:24 UTC

**Comment by rpottsoh** [comment] 2018-01-25 14:34
@martinfreedman Just because this issue is now closed doesn't mean that any interest in your ideas for improving this exercise have diminished.  The issue is closed simply because a PR was merged that was intended to "fix" this issue.

When you are free, I encourage you to open a new issue and feel free to reference the comments that have been made in this issue regarding making further improvements to the RNA-Transcription exercise.

**Comment by kytrinyx** [comment] 2018-01-26 03:47
I just wanted to mention that I'm totally cool with having a different definition than the Rosalind exercise. I didn't implement the Rosalind exercise, it was more "inspired by". I like the problem statement a lot better when we're looking at the complements rather than the equivalents between RNA and DNA.
