### ISSUE TITLE
meetup: `description.md` doesn't match up with canonical-data

### ISSUE THREAD

**Issue by m-dango** [exercism/problem-specifications#1069] opened 2018-01-04 12:22 UTC
According to the exercise description, the expected input should be a description of the date:
> you will take a description of a meetup date, and return the actual meetup date.
> For example, if given "The first Monday of January 2017", the correct meetup date is 2017/1/2.

It looks like things may have gotten mixed up in PR https://github.com/exercism/problem-specifications/pull/1050.

**Comment by ErikSchierboom** [comment] 2018-01-04 12:27
I don't see how things have gotten mixed up. With the merged PR, the input looks like this:

```json
"input": {
  "year": 2017,
  "month": 1,
  "week": "first",
  "dayofweek": "Monday"
}
```

To me, this matches exactly the example you quote above, which has four parts: "The **first** **Monday** of **January** **2017**" (emphasis on different parts).

**Comment by mienaikage** [comment] 2018-01-04 12:42
From what I gather from `description.md`, the key `description` should be the input.

**Comment by ErikSchierboom** [comment] 2018-01-04 13:16
@mienaikage Aha, but I only tried to conform to the new "input" format, and not update the existing format. 

I'm not opposed to doing what was suggested in #1006 and converting the input to a sentence, but that should be a new PR IMHO.

**Comment by rpottsoh** [comment] 2018-01-04 14:06
It appears to me that the canonical data has not agreed with the description for quite some time, I think #1050 was correct as its purpose was not to bring the test data and description into agreement.
  
The canonical data and/or the description should be updated so they agree with each other (as has been previously discussed).  It doesn't matter to me which file changes or if they both change in order to reach common ground.

**Comment by ErikSchierboom** [comment] 2018-01-04 14:18
@mienaikage Would you be interested in creating a PR for this? If so, you might want to also look at #978, which also aims to improve the meetup canonical data by introducing some grouping.

**Comment by mienaikage** [comment] 2018-01-04 14:48
I'll create a new PR shortly.

**Comment by ErikSchierboom** [comment] 2018-01-04 14:59
Great!

**Comment by mienaikage** [comment] 2018-01-15 09:56
Apologies for the delay, I'm still working on rewriting `canonical-data.json`.

**Comment by petertseng** [comment] 2018-10-05 07:29
A small request to the person who do this: Decide and explain whether to recommend that implementing language tracks must also use the full string as input (adding the parsing aspect to the required implementation for this exercise) or if instead they might feel free to continue using the structured input (in which case the problem is about turning the structured specification into a date)

**Comment by petertseng** [comment] 2018-10-05 07:33
If the person who makes that decision needs to refer back to history, that person might benefit from starting with https://github.com/exercism/exercism/commit/1e87b0018daf31335dca7133849f89255b839695 the original

**Closed** 2022-11-18 12:39 UTC
