### ISSUE TITLE
Scale Generator task: wording and tests

### ISSUE THREAD

**Issue by b10s** [exercism/problem-specifications#1640] opened 2020-02-19 12:25 UTC
1. It is difficult to understand which part of the sentence the word `major` refers to. I have feeling there is missed period or new line:
![Selection_152](https://user-images.githubusercontent.com/4618288/71672434-464ef200-2db9-11ea-8365-13283af5dc3b.png)
_**How could we interpret the `major` word in the aforementioned sentences?**_

2. Test cases have interval pattern e.g. `MmMMmMM` as input. To build scale with of 7 intervals we need 8 points, as per my naive understanding. However test expects only 7 points:

   ```
   46     description: "Minor scale with sharps",                                      
   47     tonic:       "f#",                                                           
   48     interval:    "MmMMmMM",                                                      
   49     expected:    []string{"F#", "G#", "A", "B", "C#", "D", "E"},                 
   50   },
   ```
   Thus we can ignore last interval and will pass all tests.
What says wiki somehow confirms my theory about 8 points in a scale to represent 7 intervals:
![Selection_154](https://user-images.githubusercontent.com/4618288/71673130-3fc17a00-2dbb-11ea-889c-00b3905dd8ac.png)
_**In solution, how would you expect us to interpret the last interval character in an interval pattern?**_

**Comment by yawpitch** [comment] 2020-02-19 13:22
I'm absolutely _not_ a musically-minded person, and I agree that the wording there is _terribly_ confusing, but if I understand it correctly than it should _probably_ be represented and understood as a table:

|Sharps/Flats | Major | Minor|
|--|--|--|
|Neither | C | a|
|Sharps| G, D, A, E, B, F# | e, b, f#, c#, g#, d#|
|Flats | F, Bb, Eb, Ab, Db, Gb | d, g, c, f, bb, eb |

Unfortunately I will **have** to defer to someone with more knowledge of the subject to say if that actually _helps_ make it easier to understand.

As for the notation: the major and minor scales are heptatonic; there are 7 distinct notes, 1 and 8 in the notation described in the wikipedia article are both the same tonic note (albeit 1 octave apart). So they essentially represent modular wrapping around back to the front of the list of distinct notes.

So the given example represents the individual notes found in the minor scale (with sharps) starting (and thus ending) with the tonic of f#:

|F# | G# | A | B | C# | D | E |
|--|--|--|--|--|--|--|
| 1 | 2 | b3 | 4 | 5 | b6 | 7 |
| 8 | | | | | | |

**Comment by glennj** [comment] 2020-02-19 14:04
@guygastineau this is in your domain.

**Comment by glennj** [comment] 2020-02-19 14:05
May be a duplicate of #1531

**Comment by tehsphinx** [comment] 2020-02-20 22:15
To be honest: When I did this exercise I was only able to solve it by looking at what the tests expected. The description only confused me and that although I have played the guitar for more than 20 years.

**Comment by yawpitch** [comment] 2020-02-22 14:37
Ok, after some offline discussion via email I do see one set of tests that would be valuable to add. Right now there is no test for illegal intervals, so for a tonic of `f#` you could reasonably generate the correct scale `[F#, G#, A, B, C#, D, E]` from the given legal interval `MmMMmMM`, but _also_ the illegal versions `MmMMmMm` and `MmMMmMA`.
                                                           
We probably should add some tests that expect to fail with intervals containing characters other than "m", "M", and "A", intervals greater than 12 characters long, and intervals that do not sum to exactly 12 when "m" is replaced with 1, "M" with 2, and "A" with 3.

**Comment by stwaidele** [comment] 2020-09-02 17:05
The problem is NOT that, according to the tests, f# = [F#, G#, A, B, C#, D, E] can be generated from "legal" and "illegal" intervals. The problem is that the tests expect 7 notes when there are 7 intervals given.

7 intervals should produce 8 notes. Thus f# should be "MmMMmMM" = [F#, G#, A, B, C#, D, E, F#]. The other intervals produce different notes and would fail. "MmMMmMm" should give [F#, G#, A, B, C#, D, E, F] (which probably is not a correct scale, but the correct output for the given intervals.

Alternatively, the tests could be fixed by removing the last character from the interval-strings, thus requesting only 6 intervals and expecting only 7 notes. But I think that would be "less correct" in the musical domain.

I'd love to contribute a patch, but would like to get feedback before putting too much work in.

**Comment by dzegel** [comment] 2021-11-16 08:43
coming in a bit late here but it seems this discussion has been focused on improving the explanation of how musical nots work (which I think is great) but IMO even with that I think the task is still unclear to the student. Perhaps this would be helpful https://github.com/exercism/csharp/pull/1826 ?

**Comment by dzegel** [comment] 2021-11-16 08:47
hmm it also seems that I was looking at the csharp repo not this one.
How are the two repos coordinated?
Should my PR have been made on this repo instead?

**Comment by ErikSchierboom** [comment] 2021-11-16 08:53
> How are the two repos coordinated?

We have a tool (configlet) that helps with the syncing.

> Should my PR have been made on this repo instead?

Yes please. That way, all tracks that have implemented this exercise benefit from improvements.

**Comment by dzegel** [comment] 2021-11-16 09:02
> > Should my PR have been made on this repo instead?
> 
> Yes please. That way, all tracks that have implemented this exercise benefit from improvements.

https://github.com/exercism/problem-specifications/pull/1884

**Comment by dzegel** [comment] 2021-11-16 11:58
> The problem is NOT that, according to the tests, f# = [F#, G#, A, B, C#, D, E] can be generated from "legal" and "illegal" intervals. The problem is that the tests expect 7 notes when there are 7 intervals given.
> 
> 7 intervals should produce 8 notes. Thus f# should be "MmMMmMM" = [F#, G#, A, B, C#, D, E, F#]. The other intervals produce different notes and would fail. "MmMMmMm" should give [F#, G#, A, B, C#, D, E, F] (which probably is not a correct scale, but the correct output for the given intervals.
> 
> Alternatively, the tests could be fixed by removing the last character from the interval-strings, thus requesting only 6 intervals and expecting only 7 notes. But I think that would be "less correct" in the musical domain.
> 
> I'd love to contribute a patch, but would like to get feedback before putting too much work in.

Is there consensus around this?
If so I can include this change in my PR but I'm just not familiar enough with music to make this call.

**Comment by petertseng** [comment] 2021-11-19 12:59
> The problem is NOT that, according to the tests, f# = [F#, G#, A, B, C#, D, E] can be generated from "legal" and "illegal" intervals. The problem is that the tests expect 7 notes when there are 7 intervals given.
> 
> 7 intervals should produce 8 notes. 

While I, being one person, cannot represent a consensus, my advice on the matter is:

* I think what is being said makes sense. N intervals plus a starting note is enough information to determine N + 1 notes.
* It can be seen as deficiency that we are only checking N notes, since that implies the last interval can be ignored.
* We are fortunate in that all our current intervals in canonical-data.json result in exactly a full octave, so all the scales make musical sense.
  * This may be why this change was not seen as a high priority up until this point.
  * This is confirmed by the `raise "bad test..."` lines in https://github.com/petertseng/exercism-problem-specifications/blob/verify/exercises/scale-generator/verify.rb - since none of the tests cause those lines to raise, all of the tests result in a exactly full octave.
* You (or any other contributor) would be welcome to make such a change, but if you did, you should keep it in a separate PR from your change to the description. The above-discussed change will change the canonical data.

**Comment by Skarlso** [comment] 2021-12-07 11:38
I agree that this problem is terribly confusing. I especially find `interval`s section confusing. I somewhat understand the description but I find no indication what the hell they are supposed to do to the scale and why I should care and where they come from. :) I understand that `m` is for half whatever and `M` is when there is a note between two notes. And that's it. There is no more description about what the interval is supposed to do. And don't even get me started on diatonic because I have no idea what that is. :)

I solved `hard` problems in less amount of time it takes me to parse and understand and read the description of this `easy` problem. And find out what I'm supposed to do with it. So I'm left with just reading the readme and then try to reproduce whatever it needs. But I'm no closer to understand the supposed concept that this should teach me. :)

**Comment by Skarlso** [comment] 2021-12-07 11:39
Oh yeah, I do. Music theory is frigging hard. :) And boring. :)

**Closed** 2021-12-10 05:23 UTC

**Comment by petertseng** [comment] 2021-12-10 06:54
I admit there remains no good answer to the question "why should I care about the concepts that this exercise is presenting", but I will hope that the description change at least makes things better. Of course, tracks have to incorporate those description changes.
